### PR TITLE
Feature/grouping tags

### PR DESCRIPTION
**Pull request by ljpetrova**

### CODE REVIEW

**Comment by vladoohr** [comment]
@ljpetrova I cannot see the unit tests

**Comment by natemago** [comment]
@ljpetrova please resolve the conflicts with the master branch.

**Comment by natemago** [comment]
Also, Is this complete or are we expecting unit tests for the new actions?

**Comment by ljpetrova** [comment]
@natemago The conflicts are resolved and the unit-tests are in progress.

**Comment by ljpetrova** [comment]
@natemago The unit tests are added.

**Pull request merged**
